# 1.OS Error

In [ ]:
#!pip install spacy
%pip install typing-extensions --upgrade



In [1]:
import spacy
nlp = spacy_load("en_core_web_sm")
# namespace error 

NameError: name 'spacy_load' is not defined

# 1.Solution

In [2]:
import spacy
import os

# Download the model first if not available
os.system("python -m spacy download en_core_web_sm")

# Then load
nlp = spacy.load("en_core_web_sm")


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 31.6 MB/s  0:00:00 eta 0:00:01
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')


# 2.Error: ModuleNotFoundError for TextBlob

In [3]:
from textblob import TextBlob
blob = TextBlob("TextBlob is amazing.")

ModuleNotFoundError: No module named 'textblob'

# 2.Solution

In [4]:
!pip install textblob
from textblob import TextBlob
blob = TextBlob("TextBlob is amazing.")
print(blob.sentiment)


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 624.3/624.3 kB 7.8 MB/s  0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 12.9 MB/s  0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3/3 [textblob]1/3 [nltk]
Sentiment(polarity=0.6000000000000001, subjectivity=0.9)


# 3.AttributeError                            

In [5]:
from sklearn.feature_extraction.text import CountVectorizer
texts = [123, 456]  # numeric values instead of strings
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(texts)


AttributeError: 'int' object has no attribute 'lower'

# 3.Solution

In [6]:
from sklearn.feature_extraction.text import CountVectorizer
texts = ["text one", "text two"]  # must be strings
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(texts)
print(X.toarray())


[[1 1 0]
 [0 1 1]]


# 4.Attribute Error

In [7]:
from nltk.corpus import stopwords
stop_words = stopwords.word('english')


LookupError: 
**********************************************************************
  Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('stopwords')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/stopwords

  Searched in:
    - '/Users/harikrishnan/nltk_data'
    - '/Users/harikrishnan/Documents/anaconda3/envs/myenv/nltk_data'
    - '/Users/harikrishnan/Documents/anaconda3/envs/myenv/share/nltk_data'
    - '/Users/harikrishnan/Documents/anaconda3/envs/myenv/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************


# 4.Solution

In [8]:
import nltk
nltk.download('stopwords')

from nltk.corpus import stopwords
stop_words = stopwords.words('english')
print(stop_words[:10])


['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an']


[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/harikrishnan/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


# 5.ValueError                                

In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
X = tfidf.fit_transform("single string instead of list")


ValueError: Iterable over raw text documents expected, string object received.

# 5.Solution

In [10]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
X = tfidf.fit_transform(["sentence one", "sentence two"])
print(X.toarray())

[[0.81480247 0.57973867 0.        ]
 [0.         0.57973867 0.81480247]]


# 6.NameError                                 

In [11]:
from wordcloud import WordCloud
wc = WordCloud(stopwords=STOPWORDS)


NameError: name 'STOPWORDS' is not defined

# 6.Solution

In [13]:
from wordcloud import WordCloud, STOPWORDS
wc = WordCloud(stopwords=STOPWORDS)